DROP TABLE IF EXISTS employee_stagings;

CREATE TABLE employee_stagings (
    id SERIAL PRIMARY KEY,
    import_batch_id VARCHAR(50),
    status VARCHAR(20) DEFAULT 'PENDING',
    error_message TEXT,
    nrp VARCHAR(50),
    nama VARCHAR(100),
    email VARCHAR(100),
    password VARCHAR(100),
    jabatan_raw VARCHAR(100),
    departemen_raw VARCHAR(100),
    jobsite_raw VARCHAR(100),
    status_karyawan VARCHAR(50),
    tanggal_bergabung VARCHAR(20),
    tempat_lahir TEXT,
    tanggal_lahir TEXT,
    jenis_kelamin TEXT,
    agama TEXT,
    status_pernikahan TEXT,
    golongan_darah TEXT,
    nik TEXT,
    alamat_ktp TEXT,
    alamat_domisili TEXT,
    no_hp TEXT,
    no_hp_keluarga TEXT,
    nama_keluarga TEXT,
    hubungan_keluarga TEXT,
    nama_ibu_kandung TEXT,
    no_bpjs_kesehatan TEXT,
    no_bpjs_ketenagakerjaan TEXT,
    no_npwp TEXT,
    nama_bank TEXT,
    no_rekening TEXT,
    pemilik_rekening TEXT,
    ukuran_baju TEXT,
    ukuran_sepatu TEXT,
    ukuran_celana TEXT,
    tinggi_badan TEXT,
    berat_badan TEXT,
    tanggal_pernikahan TEXT,
    tipe_kontrak_raw TEXT,
    no_sk TEXT,
    tanggal_mulai_kontrak TEXT,
    tanggal_selesai_kontrak TEXT,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_employee_stagings_import_batch_id ON employee_stagings(import_batch_id);
CREATE INDEX idx_employee_stagings_status ON employee_stagings(status);
